security:
  user:
    password: password
  ignored:
    - "*.bundle.*"
spring:
  session:
    store-type: redis
zuul: # This says "map paths with the pattern /resource/** in this server to the same paths in the remote server at localhost:9000".
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers: # all are forwarded
